Models/SalesRecord.cs
using System;
using WebApp.Models.Enums;

namespace WebApp.Models{
    public class SalesRecord {
        public int Id { get; set; }
        public DateTime Date { get; set; }
        public double Amount { get; set; }
        public SaleStatus Status { get; set; }
        public Seller Seller { get; set; }

        public int SellerId { get; set; }

        public SalesRecord() 
        {

        }

        public SalesRecord(int id, DateTime time, double amount, SaleStatus status, Seller seller) 
        {
            Id = id;
            Date = time;
            Amount = amount;
            Status = status;
            Seller = seller;
        }
    }

}

Models/View_Models/SalesRecordViewModel.cs
using System.Collections.Generic;
using WebApp.Models.Enums;

namespace WebApp.Models.View_Models
{
    public class SalesRecordViewModel
    {
        public ICollection<Seller> Sellers { get; set; }

        public SalesRecord SalesRecord { get; set; }

        public SaleStatus SaleStatus {get; set;}

    }
}

Controllers/SalesRecordsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;
using WebApp.Services;
using WebApp.Models.View_Models;
using WebApp.Models;

namespace WebApp.Controllers
{
    public class SalesRecordsController : Controller
    {

        private readonly SalesRecordsService _salesRecordService;
        private readonly SellerService _sellerService;

        public SalesRecordsController(SalesRecordsService salesRecordService, SellerService sellerService)
        {
            _salesRecordService = salesRecordService;
            _sellerService = sellerService;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> SimpleSearch(DateTime? minDate, DateTime? maxDate)
        {

            if(!minDate.HasValue)
            {
                minDate = new DateTime(DateTime.Now.Year,1,1);
            }

            if(!maxDate.HasValue)
            {
                maxDate = DateTime.Now;
            }


            ViewData["minDate"] = minDate.Value.ToString("yyyy-MM-dd");
            ViewData["maxDate"] = maxDate.Value.ToString("yyyy-MM-dd");

            var result = await _salesRecordService.FindByDateAsync(minDate,maxDate);
            return View(result);
        }

        public async Task<IActionResult> GroupingSearch(DateTime? minDate, DateTime? maxDate)
        {

            if(!minDate.HasValue)
            {
                minDate = new DateTime(DateTime.Now.Year,1,1);
            }

            if(!maxDate.HasValue)
            {
                maxDate = DateTime.Now;
            }

            ViewData["minDate"] = minDate.Value.ToString("yyyy-MM-dd");
            ViewData["maxDate"] = maxDate.Value.ToString("yyyy-MM-dd");

            var result = await _salesRecordService.FindByDateGroupingAsync(minDate,maxDate);
            return View(result);
        }

        public async Task<IActionResult> Create()
        {
            var sellers = await _sellerService.FindAllAsync();
            var viewModel = new SalesRecordViewModel{Sellers = sellers};
            return View(viewModel);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create (SalesRecord salesRecord)
        {
            await _salesRecordService.InsertAsync(salesRecord);
            return RedirectToAction(nameof(SimpleSearch));
        }
    }
}

Views/SalesRecords/Create.cshtml
@model WebApp.Models.View_Models.SalesRecordViewModel

<h2>Adicionar uma nova venda</h2>

<form asp-controller="SalesRecords" asp-action="Create">
    <label asp-for="SalesRecord.Date"> Data </label>
    <input asp-for="SalesRecord.Date" type="date" class="form-control">
    <label asp-for="SalesRecord.Amount"> Valor </label>
    <input asp-for="SalesRecord.Amount" type="numeric" class="form-control">
    <label asp-for="SalesRecord.Status">Status da venda</label>
    <br>
    <select asp-for="SaleStatus" asp-items="Html.GetEnumSelectList<WebApp.Models.Enums.SaleStatus>()" type="button" class="btn btn-primary dropdown-toggle">
        <option selected="selected" value="">Selecione uma opção</option>
    </select>
    <br>
    <div class="form-group">
        <label asp-for="SalesRecord.Seller">Vendedor</label>
        <br>
        <select asp-for="SalesRecord.SellerId" asp-items="@(new SelectList(Model.Sellers,"Id","Name"))" type="button" class="btn btn-primary dropdown-toggle"></select>
    </div>
    <br>
    <input type="submit" class="btn btn-success">
</form>

Views/SalesRecords/Index.cshtml
@model WebApp.Models.SalesRecord
<h2>Busca Simples</h2>
<div class="form-group">
    <form asp-action="SimpleSearch">    
        <strong><label for="minDate">Data de inicio</label></strong>
        <input name="minDate" type="date" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <strong><label for="maxDate">Data de término</label></strong>
        <input name="maxDate" type="date" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        <input type="submit" value="Buscar" class="btn btn-primary">
    </form>
</div>

Views/SalesRecords/SimpleSearch.cshtml
@model IEnumerable<WebApp.Models.SalesRecord>

<h2>Busca Simples</h2>

<div class="form-group">
    <form asp-action="SimpleSearch">    
        <strong><label for="minDate">Data de inicio</label></strong>
        <input  name="minDate" type="date" class="form-control" id="exampleInputEmail1" value = @ViewData["minDate"] >
        <strong><label for="maxDate">Data de término</label></strong>
        <input name="maxDate" type="date" class="form-control" id="exampleInputEmail1" value = @ViewData["maxDate"]>
        <input type="submit" value="Buscar" class="btn btn-primary">
    </form>
</div>
<div class="alert alert-dismissible alert-info">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4 class="alert-heading">Valor total:</h4>
  <p class="mb-0">R$ @Model.Sum(obj => obj.Amount)</p>
</div>
<table class="table table-striped">
    <thead>
        <tr class="table-dark">
            <th>
                 @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seller.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Seller.Department.Departamento)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
             <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seller.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Seller.Department.Departamento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Amount)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
            </tr>
        }
    </tbody>
</table>